name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # Add MySQL service
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root1234
          MYSQL_DATABASE: megacitycabs
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Debug - List directory structure
    - name: List directory structure
      run: find .

    # Step 5: Initialize MySQL database with SQL dumps
    - name: Initialize MySQL database
      run: |
        # Create a temporary script to handle the dump
        echo "SET FOREIGN_KEY_CHECKS=0;" > init_db.sql
        cat megacitycabsystem/src/main/resources/megacitycabs_dump.sql >> init_db.sql
        echo "SET FOREIGN_KEY_CHECKS=1;" >> init_db.sql
        # Execute the script
        mysql -h 127.0.0.1 -u root -proot1234 megacitycabs < init_db.sql
        rm init_db.sql

    # Step 6: Debug - Verify database content
    - name: Verify database initialization
      run: mysql -h 127.0.0.1 -u root -proot1234 megacitycabs -e "SHOW TABLES;"

    # Step 7: Build with Maven (without tests)
    - name: Build with Maven
      run: mvn clean install -DskipTests
      working-directory: megacitycabsystem

    # Step 8: Package application
    - name: Package application
      run: mvn package
      working-directory: megacitycabsystem

    # Step 9: Upload the artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: megacity-cab-artifact
        path: megacitycabsystem/target/megacitycabsystem.war
        if-no-files-found: warn
        retention-days: 30
        overwrite: true

    # Step 10: Deploy Documentation to GitHub Pages
    - name: Deploy Documentation to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ github.token }}
        publish_dir: ./megacitycabsystem/docs
